### ISSUE TITLE
Sorting of archive

### ISSUE THREAD

**Issue by jonathanwestin** [CDH-DevTeam/sodrarada-gui#16]
The archive items should be sorted oldest to newest, and if they lack date placed last.

**Comment by arildm** [comment]
Apparently, sorting in the API is complicated, because the Year field is inside the Date component. We could either move them out of the component (add new fields, move field values using SQL plumbing, remove the old fields) or upgrade to Strapi 4 (which is even more work, but should eventually be done).

For now, we fetch all the JSON data and then sort each collection in the frontend. Then we limit to 20 (#2) and discard the remaining JSON data. We then only fetch ≤20 image files for each collection.
